import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import Head from 'next/head'
import { GiHamburgerMenu } from "react-icons/gi";
import { MdOutlineDarkMode, MdLightMode } from "react-icons/md";

export const metadata: Metadata = {
  title: "Sreejit's blog",
  description: "Generated by curiosity",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en" className="dark">
        <Head>
          <link
            rel="stylesheet"
            href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css"
          />
        </Head>
      <body className="dark:bg-gray-900">
        {/* Fixed Navbar */}
        <div className="fixed top-0 left-0 w-full bg-white dark:bg-[#101826] shadow-sm z-50">
          <div className="container mx-auto p-3 ">
            <div className="flex items-center justify-between  py-1 lg:py-6">
              {/* Logo + Name */}
              <Link className="flex items-center" href="/">
                <Image
                  src="/logo.svg"
                  width={60}
                  height={60}
                  alt="Picture of the author"
                  className="mr-3"
                />
                <div className="hidden font-body text-2xl font-extrabold text-primary dark:text-white lg:block">
                  Sreejit M
                </div>
              </Link>

              {/* Navigation */}
              <div className="hidden lg:flex items-center">
                <ul className="flex items-center">
                  {["Intro", "Blog", "Categories", "Resume"].map((item) => (
                    <li key={item} className="group relative mr-6">
                      <div className="absolute left-0 bottom-0 z-20 h-0 w-full transition-all group-hover:h-2 group-hover:bg-green-300"></div>
                      <Link
                        className="relative z-30 block px-2 font-body text-xl font-bold text-primary transition-colors group-hover:text-green dark:text-white dark:group-hover:text-secondary"
                        href={`/${item.toLowerCase()}`}
                      >
                        {item}
                      </Link>
                    </li>
                  ))}
                    <MdLightMode className="text-5xl dark:text-white"/>
                </ul>
              </div>

              {/* Mobile Menu Button */}
              <div className="lg:hidden">
                <ul className="flex items-center gap-2">
                  <MdLightMode className="text-4xl dark:text-white"/>
                  <GiHamburgerMenu className="text-4xl dark:text-[#E5E5E5]"/>
                </ul>
              </div>

            </div>
          </div>
        </div>
        
        {/* Content with padding to prevent overlap */}
        <div className="pt-[72px] dark:bg-[#171730]">{children}</div>
      </body>
    </html>
  );
}
